import type { Post } from "./types";

export const posts: Post[] = [
  {
    id: "po0",
    authorId: "u1",
    kind: "NOTE",
    title: "📌 相聚使用小提醒",
    body: "歡迎新加入的家人和朋友～這裡是我們的小天地，可以發文、辦活動、投票。要更多權限隨時跟阿嬤說。記得：這裡所有人都看得到，要私訊請走 Line ♡",
    likes: 32,
    comments: 5,
    createdAt: "置頂中",
    isPinned: true,
    pinnedById: "u1",
    categoryIds: ["c-family"],
  },
  {
    id: "po1",
    authorId: "u2",
    kind: "ARTICLE",
    title: "外婆的紅燒肉食譜",
    body: "外婆昨天教我她保留了五十年的紅燒肉做法——其實秘訣是冰糖一定要先炒成焦糖色...",
    likes: 18,
    comments: 6,
    createdAt: "2 小時前",
    categoryIds: ["c-food", "c-grandpa"],
  },
  {
    id: "po2",
    authorId: "u3",
    kind: "RECOMMENDATION",
    title: "好用的露營椅推薦",
    body: "上次烤肉時用到的椅子超推！收納方便、坐墊舒服，重點是台幣 800 有找。",
    likes: 7,
    comments: 3,
    createdAt: "昨天",
    categoryIds: ["c-recommend", "c-hobby"],
  },
  {
    id: "po3",
    authorId: "u4",
    kind: "NOTE",
    body: "今天爸爸生日，我們訂了他最愛的栗子蛋糕。生日快樂爸爸 🎂",
    likes: 24,
    comments: 9,
    createdAt: "3 天前",
    categoryIds: ["c-family", "c-gift"],
  },
  {
    id: "po4",
    authorId: "u6",
    kind: "ARTICLE",
    title: "畢業十年，我們還是會吵架",
    body: "昨晚同學會結束後，我在回家的路上想了很多。十年了，這群朋友還是會吵會鬧，但散場前還是會擁抱。",
    likes: 13,
    comments: 4,
    createdAt: "5 天前",
    categoryIds: ["c-friends"],
  },
];
