import type { CustomPage } from "./types";

export const customPages: CustomPage[] = [
  {
    id: "cp1",
    slug: "grandpa-stories",
    title: "外公的軍旅故事",
    ownerId: "u1",
    excerpt: "外公在金門服役時的點點滴滴，我們一起整理出來給後輩留念。",
    cover: "linear-gradient(135deg, #D4C4A8 0%, #8B7355 100%)",
    blocks: 6,
    categoryIds: ["c-grandpa", "c-family"],
  },
  {
    id: "cp2",
    slug: "family-recipes",
    title: "我們家的食譜書",
    ownerId: "u2",
    excerpt: "媽媽、阿嬤、姑姑們最拿手的家常菜，照片 + 步驟。",
    cover: "linear-gradient(135deg, #E8B5A2 0%, #C75B3A 100%)",
    blocks: 12,
    categoryIds: ["c-food", "c-family"],
  },
  {
    id: "cp3",
    slug: "kid-album",
    title: "小毛的成長日記",
    ownerId: "u4",
    excerpt: "0 歲到現在的有趣瞬間，定期更新。",
    cover: "linear-gradient(135deg, #C5D1BB 0%, #7A8E6E 100%)",
    blocks: 24,
    categoryIds: ["c-family", "c-life"],
  },
  {
    id: "cp4",
    slug: "family-tree",
    title: "家族樹狀圖",
    ownerId: "u1",
    excerpt: "三代以內的親戚關係圖，幫年輕一輩搞清楚怎麼叫人。",
    cover: "linear-gradient(135deg, #B58FBF 0%, #6B4D78 100%)",
    blocks: 3,
    categoryIds: ["c-family"],
  },
  {
    id: "cp5",
    slug: "friends-travel-log",
    title: "朋友圈出遊紀錄",
    ownerId: "u6",
    excerpt: "Andy 整理的：大學同學歷年出遊照片 + 餐廳清單。",
    cover: "linear-gradient(135deg, #F4D4DA 0%, #D98090 100%)",
    blocks: 9,
    categoryIds: ["c-friends", "c-travel"],
  },
];
